import { useAuth } from "./authenticate/Auth";
import React, { useContext, useEffect, useState } from "react";
import { withRouter,Redirect,Route } from 'react-router-dom';
import { Form,FormControl,NavDropdown,Nav, Navbar,MenuItem,Dropdown,Table } from "react-bootstrap";
import {IconButton,Button} from '@material-ui/core';
import DeleteIcon from '@material-ui/icons/Delete';
import "./index.css";
import CheckModal from "./checkModal";
import { makeStyles } from '@material-ui/core/styles';
import { useHome } from './homeProvider';
import { auth } from "./firebase";
import overView from "./Plan/overView";
import LogIn from "./authenticate/LogIn";
